# Generated by Django 4.0.4 on 2022-05-18 05:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0003_alter_cloudprovider_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudprovider',
            name='cloud_cred_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
