# Generated by Django 4.0.4 on 2022-05-13 01:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudprovider',
            name='cloud_access_key',
            field=models.CharField(default='AWS_123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudprovider',
            name='cloud_endpoint',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cloudprovider',
            name='cloud_name',
            field=models.CharField(choices=[('AWS', 'Amazon Web Services'), ('LYC', 'Lyve Cloud by Seagate')], default='AWS', max_length=5),
        ),
        migrations.AddField(
            model_name='cloudprovider',
            name='cloud_region',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, null=True)),
                ('cloud_region', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_provider', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cloud.cloudprovider')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_bucket', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
