# Generated by Django 4.0.4 on 2022-05-21 12:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cloud', '0005_bucket_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Migration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('src_prefix', models.CharField(default='', max_length=255)),
                ('dest_prefix', models.CharField(default='', max_length=255)),
                ('filter_date_before', models.CharField(default='', max_length=16)),
                ('filter_date_after', models.CharField(default='', max_length=16)),
                ('filter_size_gte', models.IntegerField(default=0)),
                ('filter_size_lte', models.IntegerField(default=0)),
                ('total_count', models.IntegerField(default=0)),
                ('total_size', models.IntegerField(default=0)),
                ('progress_count', models.IntegerField(default=0)),
                ('progress_size', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('success_size', models.IntegerField(default=0)),
                ('fail_count', models.IntegerField(default=0)),
                ('fail_size', models.IntegerField(default=0)),
                ('max_workers', models.IntegerField(default=5)),
                ('status', models.IntegerField(choices=[(0, 'Scanning'), (1, 'Running'), (2, 'Paused'), (3, 'Completed'), (4, 'Failed')], default=2)),
                ('dest_bucket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dest_bucket', to='cloud.bucket')),
                ('src_bucket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='src_bucket', to='cloud.bucket')),
            ],
        ),
    ]
