# Generated by Django 4.0.4 on 2022-05-21 12:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloud', '0006_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='migration',
            name='created_at',
            #field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 21, 12, 37, 57, 676336, tzinfo=utc)),
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='migration',
            name='created_by',
            #field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='migration', to=settings.AUTH_USER_MODEL),
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='migration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
